version: '3'
services:
  db:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  yokkaichi:
    build: ./yokkaichi
    volumes:
      - ./data:/data
    environment:
      - WAIT_HOSTS=db:27017